### ISSUE TITLE
If hotfix contains more than one .msu file it download random file …

### ISSUE THREAD

**Issue by EskilMoe** [Marco-online/MSCatalogLTS#1]
Hi, is it possible to force Get-UpdateLinks to return the latest URL to the .msu file if the hotfix contains more the one link?

Her is a simple test:

```
$Guid = "a62b9737-1fe8-4df1-94b4-8ec61855a8d0"

$Post = @{size = 0; updateID = $Guid; uidInfo = $Guid} | ConvertTo-Json -Compress
    $Body = @{updateIDs = "[$Post]"}

    $Params = @{
        Uri = "https://www.catalog.update.microsoft.com/DownloadDialog.aspx"
        Method = "Post"
        Body = $Body
        ContentType = "application/x-www-form-urlencoded"
        UseBasicParsing = $true
    }
    $DownloadDialog = Invoke-WebRequest @Params
    $Links = $DownloadDialog.Content -replace "www.download.windowsupdate", "download.windowsupdate"
	$Regex = "downloadInformation\[0\]\.files\[0\]\.url\s*=\s*'([^']*)'"
   	
    $Links = [regex]::Matches($Links, $Regex)

    $Links.Value
```

**Comment by Marco-online** [comment]
Fixed Get-UpdateLinks should return the latest URL

**Comment by EskilMoe** [comment]
Hi, thanks for the response, but now I get this error,

2024-10 Cumulative Update for Microsoft server operating system version 24H2 for x64-based Systems (KB5044284)
Invoke-WebRequest : Invalid URI: The hostname could not be parsed.
At C:\Program Files\WindowsPowerShell\Modules\mscataloglts\Public\Save-MSCatalogUpdate.ps1:54 char:9
+         Invoke-WebRequest -Uri $Links -OutFile $OutFile

Eskil Moe

**Comment by Marco-online** [comment]
HI , thanks for the feedback! 
Get-UpdateLinks sorting KB to latest one
should be fine now

**Comment by EskilMoe** [comment]
Thanks, it looks fine now!

Eskil Moe

man. 4. nov. 2024 kl. 21:25 skrev Marco ***@***.***>:
